DROP TABLE IF EXISTS `person`;

CREATE TABLE `speciality` (
	`id` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`name` varchar(45) NOT NULL
);

CREATE TABLE `person` (
  `id` int(11) PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `prefix` varchar(45) NOT NULL,
  `firstname` varchar(45) NOT NULL,
  `lastname` varchar(45) NOT NULL,
  `speciality_id` int(11),
  FOREIGN KEY (`speciality_id`) REFERENCES `speciality`(`id`)
);

INSERT INTO `speciality` VALUES 
	(1, 'Right'),
	(2, 'Economy'),
	(3, 'Social'),
	(4, 'Numeric'),
	(5, 'Health');

INSERT INTO `person` VALUES 
	(1,'Dr.','Cortez','Champlin', 1),
	(2,'Prof.','Roscoe','Romaguera', 1),
	(3,'Dr.','Deondre','Cassin', 1),
	(4,'Prof.','Xzavier','Koepp', 1),
	(5,'Dr.','Joshuah','Thompson', 1),
	(6,'Prof.','Mayra','Kunde', 1),
	(7,'Prof.','Georgianna','Macejkovic', 2),
	(8,'Dr.','Gerson','Collins', 2),
	(9,'Dr.','Khalid','Boyle', 2),
	(10,'Dr.','Ryann','Ferry', 2),
	(11,'Mr.','Vickie','Cummerata', 2),
	(12,'Dr.','Abraham','Shields', 2),
	(13,'Dr.','Joana','Stracke', 2),
	(14,'Dr.','Angelo','Sanford', 2),
	(15,'Mr.','Kelvin','Nolan', 2),
	(16,'Dr.','Corrine','Kozey', 2),
	(17,'Dr.','Silas','Wilkinson', 2),
	(18,'Prof.','Zander','Schiller', 1),
	(19,'Dr.','Cesar','Deckow', 1),
	(20,'Mr.','Adalberto','Becker', 1),
	(21,'Dr.','Hans','King', 1),
	(22,'Mr.','Alessia','Torp', 1),
	(23,'Prof.','Merl','Stracke', 3),
	(24,'Prof.','Vladimir','King', 3),
	(25,'Dr.','Tressa','Bins', 3),
	(26,'Prof.','Zack','Batz', 3),
	(27,'Miss','Onie','Langosh', 3),
	(28,'Prof.','Leola','Runte', 3),
	(29,'Dr.','Maxie','Mraz', 3),
	(30,'Dr.','Jarrod','Beahan', 3),
	(31,'Dr.','Sierra','Kunde', 1),
	(32,'Ms.','Nora','Becker', 1),
	(33,'Prof.','Gisselle','Strosin', 1),
	(34,'Dr.','Isabelle','Dietrich', 1),
	(35,'Dr.','Chad','Heathcote', 1),
	(36,'Mrs.','Joseph','O\'Keefe', 1),
	(37,'Dr.','Jamaal','Tillman', 4),
	(38,'Dr.','Polly','DuBuque', 4),
	(39,'Prof.','John','Hirthe', 4),
	(40,'Miss','Ellis','O\'Kon', 4),
	(41,'Dr.','Karley','Runolfsson', 4),
	(42,'Ms.','Raleigh','O\'Hara', 4),
	(43,'Prof.','Michaela','Emard', 4),
	(44,'Dr.','Mireille','Smith', 1),
	(45,'Mr.','Audreanne','Feil', 1),
	(46,'Mr.','Maximillian','Kshlerin', 5),
	(47,'Mr.','Daphney','Wyman', 5),
	(48,'Prof.','Margie','Cruickshank', 5),
	(49,'Prof.','Laura','Welch', 5),
	(50,'Mrs.','Cathryn','Thompson', 5),
	(51,'Ms.','Adrien','Goodwin', 5),
	(52,'Miss','Oscar','Pacocha', 5),
	(53,'Prof.','Clara','Bosco', 5),
	(54,'Prof.','Katarina','Armstrong', 5),
	(55,'Prof.','Kayla','Moen', 5),
	(56,'Prof.','Marie','Goodwin', 5),
	(57,'Mr.','Vallie','Erdman', 5),
	(58,'Dr.','Brain','Mills', 5),
	(59,'Ms.','Adelia','Terry', 1),
	(60,'Prof.','Adell','Lakin', 1);
